// Builds the single-year mortality table q[0..122] from the WHO snapshots in data/who/
// and writes src/life/mortality.table.ts.
//
// Ages 0-84: WHO abridged nqx, assuming a constant hazard inside each age group:
//            q_x = 1 - (1 - nqx)^(1/n)
// Ages 85-121: Gompertz hazard continuous with the 80-84 group (anchored at its midpoint 82.5),
//            blended into a late-life plateau of ln 2 (q -> 0.5/yr) with a smooth minimum:
//            mu(x) = (G(x)^-4 + ln2^-4)^(-1/4),  G(x) = mu80 * exp(b * (x + 0.5 - 82.5))
//            b is solved by bisection so the model's life expectancy at 85 equals WHO's e85.
// Age 122: q = 1 (the oldest verified human lifespan; the hard cap).
//
// Usage: node scripts/mortality/build-table.mjs [--year 2019]
import { readFileSync, writeFileSync } from 'node:fs';

const yearArg = process.argv.indexOf('--year');
const YEAR = yearArg > -1 ? Number(process.argv[yearArg + 1]) : 2019;
const MAX_AGE = 122;
const PLATEAU = Math.LN2;

const nqx = JSON.parse(readFileSync(`data/who/LIFE_0000000030-${YEAR}.json`, 'utf8'));
const ex = JSON.parse(readFileSync(`data/who/LIFE_0000000035-${YEAR}.json`, 'utf8'));

function parseGroup(code) {
  const m = /^AGEGROUP_YEARS(\d\d)(?:-(\d\d)|PLUS)$/.exec(code);
  if (!m) throw new Error(`unrecognised age group ${code}`);
  const from = Number(m[1]);
  if (m[2] === undefined) return { from, n: Infinity };
  const to = Number(m[2]);
  // "00-01" is the single first year; "01-04" is ages 1..4; "05-09" is ages 5..9.
  return { from, n: from === 0 ? 1 : to - from + 1 };
}

const groups = nqx.rows.map((r) => ({ ...parseGroup(r.ageGroup), nqx: r.value })).sort((a, b) => a.from - b.from);
const e85Row = ex.rows.find((r) => r.ageGroup === 'AGEGROUP_YEARS85PLUS');
const e0Row = ex.rows.find((r) => r.ageGroup === 'AGEGROUP_YEARS00-01');
if (!e85Row || !e0Row) throw new Error('missing e0 or e85 in the ex snapshot');
const E85 = e85Row.value;

// Ages 0..84 from the abridged groups.
const q = new Array(MAX_AGE + 1).fill(NaN);
for (const g of groups) {
  if (!Number.isFinite(g.n)) continue;
  const qYear = 1 - Math.pow(1 - g.nqx, 1 / g.n);
  for (let x = g.from; x < g.from + g.n; x++) q[x] = qYear;
}
for (let x = 0; x < 85; x++) if (!Number.isFinite(q[x])) throw new Error(`no WHO value covers age ${x}`);

const g80 = groups.find((g) => g.from === 80);
const mu80 = -Math.log(1 - g80.nqx) / 5;

function oldAgeQ(b) {
  const out = [];
  for (let x = 85; x < MAX_AGE; x++) {
    const G = mu80 * Math.exp(b * (x + 0.5 - 82.5));
    const mu = Math.pow(Math.pow(G, -4) + Math.pow(PLATEAU, -4), -0.25);
    out.push(1 - Math.exp(-mu));
  }
  out.push(1);
  return out;
}

// Person-years lived in year x by someone alive at its start, assuming a constant hazard in the year.
function yearsLivedFraction(qx) {
  if (qx >= 1) return 0.5;
  if (qx <= 0) return 1;
  const mu = -Math.log(1 - qx);
  return qx / mu;
}

function e85For(b) {
  const qs = oldAgeQ(b);
  let S = 1;
  let e = 0;
  for (const qx of qs) {
    e += S * yearsLivedFraction(qx);
    S *= 1 - qx;
  }
  return e;
}

let lo = 0.01;
let hi = 0.4;
for (let i = 0; i < 200; i++) {
  const mid = (lo + hi) / 2;
  if (e85For(mid) > E85) lo = mid;
  else hi = mid;
}
const B = (lo + hi) / 2;
oldAgeQ(B).forEach((v, i) => (q[85 + i] = v));

// Summary numbers (for the log and for sanity).
const A0 = 0.15; // average fraction of the first year lived by infants who die in it
let S = 1;
let e0 = 0;
let mean = 0;
const surv = [];
for (let x = 0; x <= MAX_AGE; x++) {
  surv.push(S);
  const d = S * q[x];
  e0 += x === 0 ? (S - d) + A0 * d : S * yearsLivedFraction(q[x]);
  mean += x * d;
  S *= 1 - q[x];
}

const round = (v) => Number(v.toPrecision(12));
const body = `// GENERATED by scripts/mortality/build-table.mjs from WHO GHO ${YEAR} (GLOBAL, both sexes). Do not edit.
// q[x] is the probability of dying between exact ages x and x + 1. q[${MAX_AGE}] = 1 is the hard cap.

export const MODEL_ID = 'who-gho-${YEAR}-global-btsx-v1';

export const MODEL_META = {
  source: 'WHO Global Health Observatory, indicators LIFE_0000000030 (nqx) and LIFE_0000000035 (ex)',
  year: ${YEAR},
  gompertzB: ${round(B)},
  mu80: ${round(mu80)},
  e85Target: ${round(E85)},
  e0Who: ${round(e0Row.value)},
} as const;

export const Q: readonly number[] = [
${q.map((v, i) => `  ${round(v)}, // ${i}`).join('\n')}
];
`;
writeFileSync('src/life/mortality.table.ts', body);

console.log(`b = ${B.toFixed(5)}  mu80 = ${mu80.toFixed(5)}`);
console.log(`q0 = ${q[0].toFixed(6)}  e0(model) = ${e0.toFixed(3)} (WHO ${e0Row.value.toFixed(3)})  e85 = ${e85For(B).toFixed(4)} (WHO ${E85.toFixed(4)})`);
console.log(`mean completed lifespan = ${mean.toFixed(3)}`);
console.log(`S(5) = ${surv[5].toFixed(4)}  S(18) = ${surv[18].toFixed(4)}  S(65) = ${surv[65].toFixed(4)}  S(80) = ${surv[80].toFixed(4)}  S(90) = ${surv[90].toFixed(4)}`);
console.log(`S(100) = ${surv[100].toExponential(3)}  S(110) = ${surv[110].toExponential(3)}  S(122) = ${surv[122].toExponential(3)}`);
console.log(`q85 = ${q[85].toFixed(3)}  q95 = ${q[95].toFixed(3)}  q100 = ${q[100].toFixed(3)}  q110 = ${q[110].toFixed(3)}`);
