// Writes credits.html (a second page of the site) and CREDITS.md from the recording manifest,
// the sources lock, the facts, and the mortality metadata.
//
// Usage: node scripts/credits/build-credits.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const manifest = JSON.parse(readFileSync('audio-sources/manifest.json', 'utf8'));
const lock = JSON.parse(readFileSync('audio-sources/sources.lock.json', 'utf8'));
const facts = JSON.parse(readFileSync('src/content/facts.json', 'utf8'));
const causes = JSON.parse(readFileSync('src/content/death-causes.json', 'utf8'));
const REPO = 'https://github.com/Cantibenyam/echo-of-life';
const WHO = 'https://www.who.int/data/gho/data/themes/mortality-and-global-health-estimates/ghe-life-expectancy-and-healthy-life-expectancy';

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const shortTitle = (t) =>
  t
    .replace(/^File:/, '')
    .replace(/\.(ogg|oga|wav|flac|mp3)$/i, '')
    .replace(/ - SoundCloud - .*$/, '');

const byId = new Map(lock.recordings.map((r) => [r.id, r]));
const recs = manifest.recordings.map((m) => ({ ...m, ...byId.get(m.id) })).filter((r) => r.license);

const recItems = recs
  .map((r) => {
    const license = r.licenseUrl ? `<a href="${esc(r.licenseUrl)}">${esc(r.license)}</a>` : esc(r.license);
    const source = r.pageUrl ? `<a href="${esc(r.pageUrl)}">${esc(shortTitle(r.title))}</a>` : esc(shortTitle(r.title));
    return `        <li><span class="item-title">${esc(r.label)}</span><span class="item-meta">${source}, by ${esc(r.author)}. ${license}.</span></li>`;
  })
  .join('\n');

const factItems = facts
  .map((f) => `        <li><span class="age">${f.age}</span><a href="${esc(f.source.url)}">${esc(f.source.label)}</a></li>`)
  .join('\n');

const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <style>html,body{margin:0;background:#000;color:#fff}html{color-scheme:dark}</style>
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
    <meta name="color-scheme" content="dark" />
    <meta name="theme-color" content="#000000" />
    <title>Sounds and sources, The Echo of Life</title>
    <meta name="description" content="Where the recordings, facts and numbers in The Echo of Life come from." />
    <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
  </head>
  <!-- GENERATED by scripts/credits/build-credits.mjs. Do not edit. -->
  <body class="credits-page">
    <main class="credits">
      <a class="quiet-link back" href="./">Return to The Echo of Life</a>
      <h1>Sounds and sources</h1>
      <p class="lede">
        The music is played live in your browser, different for every year and for every life. Around it are real
        recordings of the world, and beneath each age, a fact from a public source.
      </p>

      <h2>Recordings</h2>
      <p>
        From Wikimedia Commons. Each is trimmed to its steadiest stretch, gently filtered and set to an even loudness.
        Recordings under CC BY-SA are shared here under the same license.
      </p>
      <ul class="items">
${recItems}
      </ul>

      <h2>When a life ends</h2>
      <p>
        The length of each life is drawn once, at birth, from the World Health Organization's 2019 global life table
        for both sexes (<a href="${WHO}">Global Health Observatory</a>), extended past 85 along a Gompertz curve fitted to
        WHO's life expectancy at 85. It is kept sealed on your device. The music never knows it.
      </p>
      <p>
        The causes of death shown when a life ends are the leading causes worldwide for that age group in
        ${causes.year}, from the <a href="${esc(causes.source.url)}">WHO Global Health Estimates</a>.
      </p>

      <h2>The graveyard</h2>
      <p>
        When a life ends, the name given at its start and the age it reached are kept in the graveyard, which anyone can
        visit. Names pass through a filter for unkind words. Nothing else about a visitor is stored.
      </p>

      <h2>Facts, by age</h2>
      <ol class="facts">
${factItems}
      </ol>

      <h2>Type and code</h2>
      <p>
        Set in <a href="https://github.com/productiontype/Newsreader">Newsreader</a> by Production Type, under the SIL Open
        Font License. Sound made with <a href="https://tonejs.github.io/">Tone.js</a>. The code is open:
        <a href="${REPO}">github.com/Cantibenyam/echo-of-life</a>.
      </p>
    </main>
    <script type="module" src="/src/credits.ts"></script>
  </body>
</html>
`;
writeFileSync('credits.html', html);

const md = `# Credits

The Echo of Life's music is synthesized live with Tone.js. Field recordings, facts, and mortality data come from the sources below.

## Recordings (Wikimedia Commons)

Each recording is trimmed, filtered and loudness-normalised. Recordings under CC BY-SA are redistributed under the same license.

${recs.map((r) => `- **${r.label}**: [${shortTitle(r.title)}](${r.pageUrl}) by ${r.author}, ${r.licenseUrl ? `[${r.license}](${r.licenseUrl})` : r.license}`).join('\n')}

## Mortality

WHO Global Health Observatory, 2019 global life table (both sexes): indicators LIFE_0000000030 (nqx) and LIFE_0000000035 (ex). Extended past 85 with a Gompertz curve calibrated to WHO's e85. See \`scripts/mortality/\`.

Causes of death shown when a life ends: WHO Global Health Estimates 2021 (deaths by cause, age and sex, ${causes.year}). See \`scripts/content/build-death-causes.mjs\`.

## Facts

${facts.map((f) => `- ${f.age}: [${f.source.label}](${f.source.url})`).join('\n')}

## Type and code

- Newsreader by Production Type, SIL Open Font License 1.1
- Tone.js, MIT License
`;
writeFileSync('CREDITS.md', md);
console.log(`credits: ${recs.length} recordings, ${facts.length} facts`);
