// GENERATED by scripts/audio/process.mjs. Do not edit.
import type { RecordingInfo } from './recordings/types';

export const RECORDINGS: readonly RecordingInfo[] = [
  {
    "id": "rain",
    "file": "rain.mp3",
    "duration": 40.05,
    "loop": "texture"
  },
  {
    "id": "birdsong",
    "file": "birdsong.mp3",
    "duration": 40.05,
    "loop": "texture"
  },
  {
    "id": "playground_distant",
    "file": "playground_distant.mp3",
    "duration": 40.05,
    "loop": "texture"
  },
  {
    "id": "playground_near",
    "file": "playground_near.mp3",
    "duration": 40.05,
    "loop": "texture"
  },
  {
    "id": "city",
    "file": "city.mp3",
    "duration": 40.05,
    "loop": "texture"
  },
  {
    "id": "station",
    "file": "station.mp3",
    "duration": 40.05,
    "loop": "texture"
  },
  {
    "id": "cafe",
    "file": "cafe.mp3",
    "duration": 40.05,
    "loop": "texture"
  },
  {
    "id": "kitchen_clock",
    "file": "kitchen_clock.mp3",
    "duration": 16.04,
    "loop": "pulse",
    "loopStart": 1.9855,
    "loopEnd": 13.9882
  },
  {
    "id": "grandfather_clock",
    "file": "grandfather_clock.mp3",
    "duration": 30.04,
    "loop": "pulse",
    "loopStart": 1.5265,
    "loopEnd": 29.019
  },
  {
    "id": "wind",
    "file": "wind.mp3",
    "duration": 40.05,
    "loop": "texture"
  },
  {
    "id": "sea",
    "file": "sea.mp3",
    "duration": 40.05,
    "loop": "texture"
  },
  {
    "id": "infant",
    "file": "infant.mp3",
    "duration": 30.04,
    "loop": "texture"
  },
  {
    "id": "bells",
    "file": "bells.mp3",
    "duration": 36.05,
    "loop": "texture"
  }
];
